"""Initial migration

Revision ID: e851a9977859
Revises: e4e9e54d0c3d
Create Date: 2025-07-21 10:20:38.420480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e851a9977859'
down_revision = 'e4e9e54d0c3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 